GET http://localhost:3000/expenses?page=2&pageSize=2
Content-Type: application/json

###
POST http://localhost:3000/expenses
Content-Type: application/json

{
  "date": "2025-07-16T19:50:30Z",
  "amount": 44.5,
  "type": "expense",
  "category": "shopping"
}

###
PUT http://localhost:3000/expenses/1
Content-Type: application/json

{
  "date": "2025-07-10T19:50:30Z",
  "amount": 8000.5,
  "type": "income",
  "category": "salary"
}


###
DELETE http://localhost:3000/expenses/4